<?php
// Current Event is Raleigh, NC NOV 2012
$path ="http://www.dave2dayevent.com/"; // Full URL Path (include slash at end)
$event = "Wealth Building Conference"; // Event Title
$date = "November 3rd - 4th, 2012"; // Event date, (e.g. January 1st, 2012)
$regDate = "Saturday at 8:00 am"; // Registration day and time, (e.g. Saturday at 8:00 am)
$startTime ="9:00 am"; // Event start time, (e.g. 9:00 am)
$endTime = "5:00 pm"; // Event end time, (e.g. 5:00 pm)
$day1 = "Saturday"; // What day is day 1 (add more if needed)
$day2 = "Sunday"; // What day is day 2 (add more if needed)
$days = "Saturday - Sunday"; // Day range (e.g. Saturday - Sunday)
$venue = "Four Points by Sheraton <br> 1200 Claren Circle <br> Morrisville, NC 27560 <br> 919-380-1221"; // Venue, use <br> for line breaks
$venueImage = "https://lh5.googleusercontent.com/-CgXUM8cP5Ec/T_gaxgcunnI/AAAAAABJSYQ/xO_rJq74AYc/s250-c-k/Four%2BPoints%2Bby%2BSheraton%2BRaleigh%2BDurham%2BAirport"; // Image for thank you page, get from Google.
$lengthAlpha = "Two"; // Length of event alpha value
$lengthNumeric = "2"; // Length of event numeric value
$city = "Raleigh"; // City event is taking place in
$stateFull = "North Carolina"; // State event is taking place in (Full)
$stateAbbv = "NC"; // State event is taking place in (Abbreviated)
$price = "$39.00"; // Cost of event
$infusion_name = "Wealth Conference Raleigh, NC Nov 2012"; // The name you gave the form in infusionsoft
$infusion_xid = "226adcc75897ffb450cb8975e1b27e1b"; // The XID code for the form generated by infusionsoft
$liveTag = "25651"; // Radio button live tag
$homeTag = "25653"; //Radio button home tag
$promoCode = '4205: Raleigh 2 Day 11/3/2012'; // Promocode from infusionsoft
$googAnal = "UA-32844790-3"; // Google analytics UID
$introVideo = "BC2333C7-D4AE-52BC-EDCDDEDA2D8BA84C"; // Amazon video ID
$webinarLink = "https://rementor.omnovia.com/register/69591346074944"; // Webinar link for thank you page
$embedMap = "https://maps.google.com/maps?q=Four+Points+by+Sheraton+Raleigh+Durham+Airport&hl=en&ll=35.85504,-78.822956&spn=0.014661,0.0262&cid=15102899190607340745&gl=US&t=m&z=16&iwloc=A&amp;iwloc=near"; //Google Map Embed Code
?>